stages:
  - name: deploy
    if: branch = master

jobs:
  include:
  - stage: deploy
    name: lightsail
    language: generic
    dist: trusty
    sudo: false
    addons:
      ssh_known_hosts:
      - hanneshertach.com
    before_script:
    - openssl aes-256-cbc -K $encrypted_b6400612d065_key -iv $encrypted_b6400612d065_iv -in lightsailkey.pem.enc -out lightsailkey.pem -d
    - eval "$(ssh-agent -s)"
    - mv lightsailkey.pem ~/.ssh/lightsailkey.pem
    - chmod 600 ~/.ssh/lightsailkey.pem
    script:
    - "cat .travisdeploy.sh | ssh -i ~/.ssh/lightsailkey.pem ubuntu@hanneshertach.com"
