version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "4567:4567"
    volumes:
      - ./uploads:/uploads
    labels:
      - "caddy.targetpath=/"
      - "caddy.targetport=4567"
      - "caddy.address=blog.hanneshertach.com"
      - "caddy.proxy.transparent="
  db:
    image: mysql
    restart: always
    volumes:
      - ./database/db_data:/var/lib/mysql
      - ./database:/etc/database-init
    command: --init-file /etc/database-init/initdb.sql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

networks:
  default:
    external:
      name: web
