version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - "4567:4567"
    labels:
      caddy.targetpath: "/"
      caddy.targetport: "4567"
      caddy.address: "blog.hanneshertach.com"
  db:
    image: mysql
    volumes:
      - ./database/db_data:/var/lib/mysql
      - ./database:/etc/database-init
      - ./uploads:/etc/uploads
    command: --init-file /etc/database-init/initdb.sql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
