version: '3'
services:
  web:
    depends_on:
      - mysql
    build: .
    ports:
      - "4567:4567"
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    volumes:
      - ./database/db_data:/var/lib/mysql
      - ./database:/etc/database-init
    command: --init-file /etc/database-init/initdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: wp
